name: windows-tests

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  tests:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --depth=1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn resilience test:unit
